Penultimate stage of migration.

diff --git a/sh/bash/profile b/sh/bash/profile
--- a/sh/bash/profile
+++ b/sh/bash/profile
@@ -1,6 +1,8 @@
-# ~/.profile
-# Sourced by ~/.bash_profile, ~/.zprofile, etc.
-# Shell context: ( log, sc=user )
+# ~/.bash_profile 
+# Default login-shell loading order:
+#       1. /etc/profile
+#       2. [ ~/.bash_profile ] || [ ~/.bash_login ] || [ ~/.profile ]
+# Shell context: ( log, sh=bash, sc=usr )
 # {{{ Explanation
 # If a field is unset in the context tuple, assume it is unspecified and may vary
 #       i[nteractive] (bool)    `[ -n "$PS1" ] && echo 1 || echo 0`
@@ -11,6 +13,7 @@
 #       sh[elltype]             { b[ash], z[sh], k[sh], ... }
 # }}}
 
+# Helpers
 [ -z "$HELPERS_LAZY_LOADER" ] && \
    HELPERS_LAZY_LOADER="$HOME/.config/sh/scripts/helpers_lazy_loader.sh"
 if [ -f "$HELPERS_LAZY_LOADER" ]; then
@@ -22,7 +25,22 @@ else
    return 127 2>/dev/null || exit 127
 fi
 
-source_with_debug "$HOME/.config/sh/path" '~/.profile' '~/.config/sh/path'
-source_with_debug "$HOME/.config/sh/env" '~/.profile' '~/.config/sh/env'
+source_with_debug "$HOME/.profile" '~/.bash_profile' '~/.profile'
+
+# Don't run if non-interactive
+[ -z "$INTERACTIVE_GUARD" ] && \
+   INTERACTIVE_GUARD="$HOME/.config/sh/scripts/interactive_guard.sh"
+if [ -f "$INTERACTIVE_GUARD" ]; then
+   if ! source_with_debug "$INTERACTIVE_GUARD" '~/.bash_profile' \
+      '~/.config/sh/scripts/interactive_guard.sh'; then
+      return 1
+   fi
+else
+   echo "Interactive guard not found: $INTERACTIVE_GUARD" >&2
+   return 127
+fi
+
+# Sourcing
+source_with_debug "$HOME/.bashrc" '~/.bash_profile' '~/.bashrc'
 
 true # explicitly signal success without returning if sourced
